In [5]:
import pandas as pd
correlations = pd.read_csv("data/correlations.csv", index_col=0)
topics = pd.read_csv("generated_data/new_topics.csv", index_col=0)
topics2 = pd.read_csv("data/topics_translate.csv", index_col=0)

In [9]:
display(correlations)

                                                      content_ids
topic_id
t_00004da3a1b2  c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...
t_00068291e9a4  c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...
t_00069b63a70a                                     c_11a1dc0bfb99
t_0006d41a73a8  c_0c6473c3480d c_1c57a1316568 c_5e375cf14c47 c...
t_0008768bdee6       c_34e1424229b4 c_7d1a964d66d5 c_aab93ee667f4
...                                                           ...
t_fff830472691                      c_61fb63326e5d c_8f224e321c87
t_fff9e5407d13  c_026db653a269 c_0fb048a6412c c_20de77522603 c...
t_fffbe1d5d43c                      c_46f852a49c08 c_6659207b25d5
t_fffe14f1be1e                                     c_cece166bad6a
t_fffe811a6da9                                     c_92b8fad372ee

[61517 rows x 1 columns]

In [10]:
display(topics.loc[topics["level"]==0])

,title,description,channel,category,level,language,parent,has_content,description_translate,title_translate
id,,,,,,,,,,
t_0325dce6b388,CBSE,CBSE,ef2088,supplemental,0,en,NaN,False,CBSE,CBSE
t_0396c73309a7,Algebra 2,Algebra 2,01dbc1,supplemental,0,en,NaN,False,Algebra 2,Algebra 2
t_04b58233425c,Khan Academy (Português (Brasil)),Khan Academy (Português (Brasil)),8e286a,source,0,pt,NaN,False,Khan Academy (Brazil),Khan Academy (Brazil)
t_055869c77b48,Form 4 Chemistry,Form 4 Chemistry,5de4e5,aligned,0,en,NaN,False,Form 4 Chemistry,Form 4 Chemistry
t_056befe7434a,Khan Academy (Português (Portugal)),Khan Academy (Português (Portugal)),f9b74f,source,0,pt,NaN,False,Khan Academy (English (Portugal)),Khan Academy (English (Portugal))
...,...,...,...,...,...,...,...,...,...,...
t_fa03a876a7dd,DIGITAL EDUCATION WITH MEHUL,DIGITAL EDUCATION WITH MEHUL,5223e0,supplemental,0,gu,NaN,False,DIGHT EDUCATION,DIGHT EDUCATION
t_fb7502ae1264,Maharashtra State Class 3 to 9 (English),Maharashtra State Class 3 to 9 (English),8bbad6,supplemental,0,en,NaN,False,Maharashtra State Class 3 to 9 (English),Maharashtra State Class 3 to 9 (English)
t_fc36634bb417,Camara Education - Ethiopia,Camara Education - Ethiopia,8afc0b,supplemental,0,en,NaN,False,Camara Education - Ethiopia,Camara Education - Ethiopia
t_fe5ced2643b3,CREE,CREE,6e90a7,aligned,0,es,NaN,False,BELIEVE,BELIEVE
t_fe5f4a411d3b,Sikana (русский язык),Sikana (русский язык),28ffa8,source,0,ru,NaN,False,Sikana (Russian),Sikana (Russian)

In [11]:
topics.iloc[4791]

title                    قناة كم كلمة لتمكين المعلّمين الناطقين باللغة ...
description              قناة كم كلمة لتمكين المعلّمين الناطقين باللغة ...
channel                                                             8dd5f3
category                                                            source
level                                                                    0
language                                                                ar
parent                                                                 NaN
has_content                                                           True
description_translate    How many words to empower Arabic-speaking teac...
title_translate          How many words to empower Arabic-speaking teac...
Name: t_10035396d740, dtype: object